### ISSUE TITLE
holidays are included in summation

### ISSUE THREAD

**Issue by 5chdn** [lukas-schulze/hpi-stundennachweis#5]
![screenshot at 2016-11-06 13-29-03](https://cloud.githubusercontent.com/assets/15729797/20037682/386b794a-a425-11e6-84ad-cdea6f3994c3.png)

I'm not sure, is this a bug or a feature?

**Comment by schulluk** [comment]
If you have days you normally work on (e.g. you work always Mondays and Fridays), than you get the hours paid which fall on a holiday.

I asked the accounting department which told me so.

**Comment by 5chdn** [comment]
thanks :+1:
